server:
  port: 8025
spring:
  application:
    name: server-03
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8023/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}